name: Keep Supabase Active

on:
  schedule:
    - cron: '0 6 * * *'   # Every day at 11:30 AM IST

  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl \
            -H "apikey: sb_publishable_HHMwxDWdnQylh6icCh0XZQ_r91grAe4" \
            -H "Authorization: Bearer sb_publishable_HHMwxDWdnQylh6icCh0XZQ_r91grAe4" \
            "https://jwuoyuhyviqadtmnwgha.supabase.co/rest/v1/laptops?select=id&limit=1"
